import 'dart:convert';
import 'dart:ui';

import 'package:quax/client/accounts.dart';
import 'package:quax/client/headers.dart';
import 'package:quax/generated/l10n.dart';
import 'package:quax/utils/lru_cache.dart';
import 'package:http/http.dart' as http;
import 'package:logging/logging.dart';

class TranslationAPIResult {
  final bool success;
  final dynamic body;
  final String? errorMessage;

  TranslationAPIResult({required this.success, required this.body, this.errorMessage});
}

class TranslationAPI {
  static final log = Logger('TranslationAPI');

  /// What X already translated, keyed by source language and post id. Bounded
  /// and in-memory on purpose: the previous store went to SharedPreferences,
  /// which is read whole at startup, and it never expired — and it was never
  /// read back either, since the load path compared a JSON String to `true`.
  /// Re-tapping the button inside one card is already covered by the widget's
  /// own `_translatedParts`, so this only spares a repeat for a card that was
  /// rebuilt in between.
  static final LruCache<String, Map<String, dynamic>> _translated = LruCache(200);

  static Future<TranslationAPIResult> translate(
      Locale locale, String id, List<String> text, String sourceLanguage) async {
    final cacheKey = '$sourceLanguage.$id';
    final cached = _translated.get(cacheKey);
    if (cached != null) {
      return TranslationAPIResult(success: true, body: cached);
    }

    final formData = {'id': id, 'dst_lang': locale.toLanguageTag(), 'content_type': 'POST'};

    Future<http.Response> getTranslation() async {
      final translationUri = Uri.https('api.x.com', '/2/grok/translation.json');
      return await http.post(translationUri, body: jsonEncode(formData), headers: {
        ...await TwitterHeaders.getHeaders(translationUri, await pickAuthHeader()),
        'Content-Type': 'text/plain;charset=UTF-8',
        'Accept-Encoding': 'gzip, deflate, br, zstd'
      });
    }

    const int numberOfRetries = 3;

    for (int i = 0; i < numberOfRetries; ++i) {
      try {
        final response = await parseResponse(await getTranslation(), L10n.current.translation_request_failed);
        if (response.success && response.body is Map<String, dynamic>) {
          _translated.set(cacheKey, response.body as Map<String, dynamic>);
        }
        return response;
      } on FormatException {
        // Wait a bit while the translation is fully generated by Grok
        await Future.delayed(Duration(seconds: 1));
      }
    }
    return TranslationAPIResult(success: false, body: {}, errorMessage: L10n.current.translation_not_ready);
  }

  static Future<TranslationAPIResult> parseResponse(http.Response response, String errorUnableTo) async {
    final utf8Response = utf8.decode(response.bodyBytes);
    final body = jsonDecode(utf8Response);
    log.info("Translation result: $body");
    if (response.statusCode == 200 && body is Map<String, dynamic>) {
      if (body.containsKey("error")) {
        final error = body['error'];
        final message = error is Map
            ? error['message'] ?? error['code'] ?? ''
            : error?.toString() ?? '';
        return TranslationAPIResult(success: false, body: body, errorMessage: message);
      }
      return TranslationAPIResult(success: true, body: body);
    }

    // A 400 can answer with HTML or a shape this code doesn't know; guessing at
    // `body['error']` would throw out of here and past the caller's retry.
    final rawError = body is Map ? body['error'] : null;

    String message = '';

    switch (response.statusCode) {
      case 400:
        // The API answers with just "<language> is not supported"; the code
        // cannot make a sentence out of that on its own.
        final unsupported = rawError is String
            ? RegExp(r"^(\w+) is not supported$").firstMatch(rawError)?.group(1)
            : null;

        message = unsupported != null
            ? L10n.current.translation_language_unsupported(unsupported)
            : rawError?.toString() ?? errorUnableTo;
        break;
      case 403:
        message = L10n.current.translation_banned;
        break;
      case 429:
        message = L10n.current.translation_rate_limited;
        break;
      case 500:
        message = L10n.current.translation_service_failed;
        break;
      default:
        message = errorUnableTo;
    }

    return TranslationAPIResult(success: false, body: body, errorMessage: message);
  }
}
